version: '3'
services:
  web:
   image: nginx:alpine
   ports:
     - 8080:80
   volumes:
     #nginxの設定ファイルをインポートさせる
     - ./docker_files/nginx_d/nginx.conf:/etc/nginx/conf.d/default.conf

  app:
   build: ./docker_files/php_d
   volumes:
     #カレントディレクトリにマウント
     - ./:/var/www/html

  db:
   image: mysql:latest
   environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
   ports:
     - 3306:3306
