version: '3'
services:
  web:
   image: nginx:1.17.1-alpine
   container_name: "${PJ_NAME}_web"
   ports:
     - 8080:80 # 左辺で指定したポートにアクセスすると、ポート80にフォワード
   volumes:
     # nginxの設定ファイルをインポートさせる
     - ./docker_files/nginx/default.conf.pre:/etc/nginx/conf.d/default.conf.pre
   # default.confに環境変数$PJ_NAMEを読ませる
   environment:
     - PJ_NAME=${PJ_NAME}
   command:
     /bin/sh -c "envsubst '$$PJ_NAME' < /etc/nginx/conf.d/default.conf.pre > 
     /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
   depends_on:
     - app

  app:
   build:
     context: ./docker_files/php
   container_name: "${PJ_NAME}_app"
   volumes:
     # srcディレクトリにマウント
     - ./src:/var/www/html
   depends_on:
     - db
     - kvs

  db:
   image: mysql:8.0.16
   container_name: "${PJ_NAME}_db"
   environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
   volumes:
     - ./docker_files/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306

  kvs:
   image: redis:5.0.5-alpine3.10
   container_name: "${PJ_NAME}_kvs"
   ports:
     - 6379:6379
