version: '3'
services:
  web:
   image: nginx:alpine
   ports:
     - 8080:80
   volumes:
     - ./docker_files/nginx_d/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
   image: php:fpm-alpine
   volumes:
     - ./:/var/www/html
