version: '3'
services:
  web:
   image: nginx:1.17.1-alpine
   ports:
     - 8080:80
   volumes:
     # nginxの設定ファイル
     - ./docker_files/nginx/default.conf.pre:/etc/nginx/conf.d/default.conf.pre
   environment:
     # default.confに環境変数を渡す
     - PJ_NAME=${PJ_NAME}
   command:
     /bin/sh -c "envsubst '$$PJ_NAME' < /etc/nginx/conf.d/default.conf.pre > 
     /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
   depends_on:
     - app

  app:
   build:
     context: ./docker_files/php
   volumes:
     - ./src:/var/www/html
     # Laravelのenvファイル
     - ./docker_files/env/env_all:/var/www/html/${PJ_NAME}/.env
   depends_on:
     - db
     - imdb

  db:
   image: mysql:8.0.16
   environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
   volumes:
     - ./docker_files/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
   ports:
     - 3306:3306

  imdb:
   image: redis:5.0.5-alpine3.10
   ports:
     - 6379:6379
