version: '3'
services:
  web:
   image: nginx:alpine
   ports:
     - 8080:80 # 左辺で指定したポートにアクセスすると、ポート80にフォワード
   volumes:
     # nginxの設定ファイルをインポートさせる
     - ./nginx_d/default.conf.pre:/etc/nginx/conf.d/default.conf.pre
   # default.confに環境変数$PJ_NAMEを読ませる
   environment:
     - PJ_NAME=${PJ_NAME}
   command:
     /bin/sh -c "envsubst '$$PJ_NAME' < /etc/nginx/conf.d/default.conf.pre > 
     /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  app:
   build:
     context: ./php_d
     args:
      - PJ_NAME=${PJ_NAME} # Dockerfileに環境変数を渡す
   volumes:
     # 一つ上のディレクトリにマウント
     - ../:/var/www/html
   env_file: .env

  db:
   image: mysql:latest
   environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
   volumes:
     - ./mysql_d:/docker-entrypoint-initdb.d
   ports:
     - 3306:3306

  kvs:
   image: redis:alpine
   ports:
     - 6379:6379
